version: "3"
services:
  frontend:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
