version: "3"
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/testdb?schema=public
      - TMDB_API_KEY=SUA_TMDB_API_KEY
      - JWT_SECRET=SUA_JWT_SECRET
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev --name init && npm run dev"

  frontend:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
